// vue/calculator/src/components/Calculator.vue
<template>
  <div class="calculator">
    <Display :value="displayValue" />
    <Button label="AC" triple @btn-click="clear" />
    <Button label="÷" operation @btn-click="setOperation" />
    <Button label="7" @btn-click="appendDigit" />
    <Button label="8" @btn-click="appendDigit" />
    <Button label="9" @btn-click="appendDigit" />
    <Button label="x" operation @btn-click="setOperation" />
    <Button label="4" @btn-click="appendDigit" />
    <Button label="5" @btn-click="appendDigit" />
    <Button label="6" @btn-click="appendDigit" />
    <Button label="-" operation @btn-click="setOperation" />
    <Button label="1" @btn-click="appendDigit" />
    <Button label="2" @btn-click="appendDigit" />
    <Button label="3" @btn-click="appendDigit" />
    <Button label="+" operation @btn-click="setOperation" />
    <Button label="0" double @btn-click="appendDigit" />
    <Button label="." @btn-click="appendDigit" />
    <Button label="=" operation @btn-click="setOperation" />
  </div>
</template>

<script>
import Button from "./Button";
import Display from "./Display";

export default {
  data: function () {
    return {
      displayValue: "0",
      mustClearDisplay: false,
      operation: null,
      values: [0, 0],
      activeValue: 0,
    };
  },
  components: {
    Button,
    Display,
  },
  methods: {
    clear() {
      Object.assign(this.$data, this.$options.data.apply(this));
    },
    setOperation(operation) {
      this.mustClearDisplay = true;

      if (operation !== "=") this.operation = operation;

      if (this.activeValue === 0) {
        this.activeValue = 1;
      } else {
        const values = this.values;

        let result = 0;
        switch (this.operation) {
          case "+":
            result = values[0] + values[1];
            break;
          case "-":
            result = values[0] - values[1];
            break;
          case "x":
            result = values[0] * values[1];
            break;
          case "÷":
            result = values[0] / values[1];
            break;
          default:
            result = this.values[0];
            break;
        }

        this.activeValue = 0;
        this.values[0] = result;
        this.values[1] = 0;

        this.displayValue = `${result}`;
      }
    },
    appendDigit(digit) {
      if (this.displayValue.includes(".") && digit === ".") return;

      if (this.displayValue === "0" && digit !== ".")
        this.mustClearDisplay = true;

      if (this.mustClearDisplay) this.displayValue = "";

      this.displayValue += digit;
      this.mustClearDisplay = false;

      if (digit !== ".") {
        const activeValue = this.activeValue;
        const values = this.values;

        const displayValue = this.displayValue;
        values[activeValue] = parseFloat(displayValue);

        this.values = values;
      }
    },
  },
};
</script>

<style>
.calculator {
  width: 320px;
  border-radius: 5px;
  overflow: hidden;

  display: grid;
  grid-template-columns: repeat(4, 25%);
  grid-template-rows: 1fr repeat(5, 48px);
}
</style>

// react/calculator/src/components/calculator/index.jsx
import React, { Component } from 'react'
import Display from '../display'
import Button from '../button'
import './style.css'

const initialState = {
  displayValue: '0',
  mustClearDisplay: false,
  operation: null,
  values: [0, 0],
  activeValue: 0
}

export default class Calculator extends Component {
  constructor(props) {
    super(props)
    this.state = { ...initialState }
  }

  clearMemory = () => {
    this.setState({ ...initialState })
  }

  setOperation = operation => {
    const updatedState = this.state

    updatedState.mustClearDisplay = true

    if (operation !== '=')
      updatedState.operation = operation

    if (this.state.activeValue === 0) {
      updatedState.activeValue = 1
    }
    else {
      const values = updatedState.values

      let result = 0
      switch (updatedState.operation) {
        case '+':
          result = values[0] + values[1]
          break
        case '-':
          result = values[0] - values[1]
          break
        case 'x':
          result = values[0] * values[1]
          break
        case '÷':
          result = values[0] / values[1]
          break
        default:
          result = updatedState.values[0]
          break
      }

      updatedState.activeValue = 0
      updatedState.values[0] = result
      updatedState.values[1] = 0

      updatedState.displayValue = `${result}`
    }

    this.setState(updatedState)
  }

  appendDigit = digit => {
    const updatedState = this.state

    if (updatedState.displayValue.includes('.') && digit === '.')
      return

    if (updatedState.displayValue === '0' && digit !== '.')
      updatedState.mustClearDisplay = true

    if (updatedState.mustClearDisplay)
      updatedState.displayValue = ''

    updatedState.displayValue += digit
    updatedState.mustClearDisplay = false

    if (digit !== '.') {
      const activeValue = updatedState.activeValue
      const values = updatedState.values

      const displayValue = updatedState.displayValue
      values[activeValue] = parseFloat(displayValue)

      updatedState.values = values
    }

    this.setState(updatedState)
  }

  render() {
    return (
      <div className="calculator">
        <Display value={this.state.displayValue} />
        <Button label="AC" click={this.clearMemory} triple />
        <Button label="÷" click={this.setOperation} operation />
        <Button label="7" click={this.appendDigit} />
        <Button label="8" click={this.appendDigit} />
        <Button label="9" click={this.appendDigit} />
        <Button label="x" click={this.setOperation} operation />
        <Button label="4" click={this.appendDigit} />
        <Button label="5" click={this.appendDigit} />
        <Button label="6" click={this.appendDigit} />
        <Button label="-" click={this.setOperation} operation />
        <Button label="1" click={this.appendDigit} />
        <Button label="2" click={this.appendDigit} />
        <Button label="3" click={this.appendDigit} />
        <Button label="+" click={this.setOperation} operation />
        <Button label="0" click={this.appendDigit} double />
        <Button label="." click={this.appendDigit} />
        <Button label="=" click={this.setOperation} operation />
      </div>
    )
  }
}
