// angular/crud/frontend/src/views/home/home.component.ts
import { Component } from '@angular/core';
import { HeaderService } from 'src/components/header/header.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent {

  constructor(private headerService: HeaderService) {
    this.headerService.data = {
      title: 'Início',
      iconName: 'home',
      routeURL: '/'
    }
  }

}

<div class="home">
  <mat-card class="card">
    <mat-card-title class="title">Bem vindo !</mat-card-title>
    <mat-card-subtitle class="subtitle">
      Sistema para exemplificar a construção de um cadastro em Angular.
    </mat-card-subtitle>
  </mat-card>
</div>

// react/crud/frontend/src/pages/home/index.jsx
import React from 'react'
import Header from '../../components/header'
import Content from '../../components/content'
import './style.css'

export default function Home() {
  return (
    <div className="home">
      <div className="home__header">
        <Header
          icon="home"
          title="Início"
          description="Segundo exercício do capítulo de React"
        />
      </div>
      <div className="home__content">
        <Content>
          <div className="h3">Bem vindo !</div>
          <hr />
          <p>Sistema para exemplificar a construção de um cadastro de usuário feito em React.</p>
        </Content>
      </div>
    </div>
  )
}
